apiVersion: v1
kind: Secret
metadata:
  name: {{ include "step-ca.fullname" . }}-provisioner-secrets
  labels:
    app.kubernetes.io/name: {{ include "step-ca.name" . }}
    helm.sh/chart: {{ include "step-ca.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  passwd: '{{ randAlphaNum 16 | b64enc }}'
