include:
  - base_image_input.yaml
  - initrd_build_input.yaml
  - image_build_input.yaml

stages:
  - base image build
  - initrd build
  - image build

.base_image_build: &base_image_build
  stage: base image build
  extends: .base_image_vars
  image: registry.example.com/example-namespace/anchor-build-tools:latest
  before_script:
    - export AUTH_FILE="./registry_auth.cfg"
    - echo "$DOCKER_AUTH_CONFIG" > "$AUTH_FILE"
  script:
    - ./base_image/build.sh

base image build:
  <<: *base_image_build
  when: manual
  except:
    - base_image_build
    - initrd_build
    - image_build

base image build (automatic):
  <<: *base_image_build
  only:
    - base_image_build

.initrd_build: &initrd_build
  stage: initrd build
  extends: .initrd_build_vars
  image: registry.example.com/example-namespace/anchor-build-tools:latest
  artifacts:
    paths:
      - output/
    expire_in: 1 week
  before_script:
    - export AUTH_FILE="./registry_auth.cfg"
    - echo "$DOCKER_AUTH_CONFIG" > "$AUTH_FILE"
  script:
    - ./initrd_build/build.sh

initrd build:
  <<: *initrd_build
  when: manual
  except:
    - base_image_build
    - initrd_build
    - image_build

initrd build (automatic):
  <<: *initrd_build
  only:
    - initrd_build

.image_build: &image_build
  stage: image build
  image: registry.example.com/example-namespace/anchor-build-tools:latest
  extends: .build_image_vars
  before_script:
    - export AUTH_FILE="./registry_auth.cfg"
    - echo "$DOCKER_AUTH_CONFIG" > "$AUTH_FILE"
    - export MESSAGE="${CI_COMMIT_MESSAGE}"
    - export CI_SHORT_SHA="${CI_COMMIT_SHA:0:6}"
    - export USER=$GITLAB_USER_NAME
  script:
      # Build the image
    - image_build/build.sh

image build:
  <<: *image_build
  when: manual
  except:
    - base_image_build
    - initrd_build
    - image_build

image build (automatic):
  <<: *image_build
  only:
    - image_build
