---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ include "chart-repo.name" . }}-nginx
  labels:
    app: {{ include "chart-repo.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec: {}
status:
  dockerImageRepository: ''
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ include "chart-repo.name" . }}-repowatch
  labels:
    app: {{ include "chart-repo.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec: {}
status:
  dockerImageRepository: ''
