apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart-repo.fullname" . }}
  labels:
    app: {{ include "chart-repo.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: webhook
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: {{ include "chart-repo.name" . }}
  type: ClusterIP
