---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "helm-operator.fullname" . }}
  labels:
    app: {{ template "helm-operator.name" . }}
    chart: {{ template "helm-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "helm-operator.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
      {{- if .Values.prometheus.enabled }}
        prometheus.io/scrape: "true"
      {{- end }}
      {{- if .Values.podAnnotations }}
      {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- end }}
      labels:
        app: {{ template "helm-operator.name" . }}
        release: {{ .Release.Name }}
      {{- if .Values.podLabels }}
      {{- range $key, $value := .Values.podLabels }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- end }}
    spec:
      {{- if .Values.runAsUser }}
      securityContext:
        runAsUser: {{ .Values.runAsUser }}
        runAsGroup: {{ .Values.runAsUser }}
      {{- end }}
      serviceAccountName: {{ template "helm-operator.serviceAccountName" . }}
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
      volumes:
      {{- if .Values.git.ssh.known_hosts }}
      - name: sshknownhosts
        configMap:
          name: {{ template "helm-operator.fullname" . }}-ssh-config
          defaultMode: 0600
      {{- end }}
      {{- if .Values.git.config.enabled }}
      - name: git-config
        secret:
          secretName: {{ include "git.config.secretName" . }}
          defaultMode: 0400
      {{- end }}
      {{- if .Values.git.ssh.secretName}}
      - name: git-key
        secret:
          secretName: {{ .Values.git.ssh.secretName }}
          defaultMode: 0400
          items:
            - key: {{ .Values.git.ssh.secretKey }}
              path: identity
      {{- end }}
      {{- if .Values.git.ssh.configMapName }}
      - name: sshconfig
        configMap:
          name: {{ .Values.git.ssh.configMapName }}
          items:
            - key: {{ .Values.git.ssh.configMapKey | default "config" }}
              path: config
          defaultMode: 0400
      {{- end }}
      {{- if .Values.configureRepositories.enable }}
      - name: {{ .Values.configureRepositories.volumeName | quote }}
        secret:
          secretName: {{ .Values.configureRepositories.secretName | quote }}
      - name: {{ .Values.configureRepositories.cacheVolumeName | quote }}
        emptyDir: {}
      {{- end }}
      {{- if .Values.initPlugins.enable }}
      - name: {{ .Values.initPlugins.cacheVolumeName | quote }}
        emptyDir: {}
      {{- end }}
      {{- if .Values.extraVolumes }}
{{ toYaml .Values.extraVolumes | indent 6 }}
      {{- end }}
{{- if or .Values.initContainers .Values.initPlugins.enable }}
      initContainers:
{{- if .Values.initContainers }}
{{ toYaml .Values.initContainers | indent 6 }}
{{- end }}
{{- if .Values.initPlugins.enable }}
{{- include "helm-operator.initPlugins" . | indent 6 }}
{{- end }}
{{- end }}
      containers:
      - name: flux-helm-operator
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 3030
        livenessProbe:
          httpGet:
            port: 3030
            path: /healthz
          initialDelaySeconds: 1
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            port: 3030
            path: /healthz
          initialDelaySeconds: 1
          timeoutSeconds: 5
        volumeMounts:
        {{- if .Values.git.ssh.secretName}}
        - name:  git-key
          mountPath: /etc/fluxd/ssh
          readOnly: true
        {{- end }}
        {{- if .Values.git.ssh.known_hosts }}
        - name: sshknownhosts
          mountPath: /etc/ssh/ssh_known_hosts
          subPath: known_hosts
          readOnly: true
        {{- end }}
        {{- if .Values.git.ssh.configMapName }}
        - name: sshconfig
          mountPath: /helm/.ssh/
          readOnly: true
        {{- end }}
        {{- if .Values.git.config.enabled }}
        - name: git-config
          mountPath: /helm/.gitconfig
          subPath: gitconfig
          readOnly: true
        {{- end }}
        {{- if .Values.configureRepositories.enable }}
        - name: {{ .Values.configureRepositories.volumeName | quote }}
          mountPath: /helm/.helm/repository/repositories.yaml
          subPath: repositories.yaml
          readOnly: true
        {{- if contains "v2" .Values.helm.versions }}
        - name: {{ .Values.configureRepositories.cacheVolumeName | quote }}
          mountPath: /var/fluxd/helm/repository/cache
          subPath: v2
        {{- end }}
        {{- if contains "v3" .Values.helm.versions }}
        - name: {{ .Values.configureRepositories.cacheVolumeName | quote }}
          mountPath: /helm/.cache/helm/repository
          subPath: v3
        {{- end }}
        {{- end }}
        {{- if .Values.initPlugins.enable }}
        {{- if contains "v2" .Values.helm.versions }}
        - name: {{ .Values.initPlugins.cacheVolumeName | quote }}
          mountPath: /var/fluxd/helm/cache/plugins/
          subPath: v2
        - name: {{ .Values.initPlugins.cacheVolumeName | quote }}
          mountPath: /var/fluxd/helm/plugins
          subPath: v2-config
        {{- end }}
        {{- if contains "v3" .Values.helm.versions }}
        - name: {{ .Values.initPlugins.cacheVolumeName | quote }}
          mountPath: /helm/.cache/helm/plugins
          subPath: v3
        - name: {{ .Values.initPlugins.cacheVolumeName | quote }}
          mountPath: /helm/.local/share/helm/plugins
          subPath: v3-config
        {{- end }}
        {{- end }}
        {{- if .Values.extraVolumeMounts }}
{{ toYaml .Values.extraVolumeMounts | indent 8 }}
        {{- end }}
        args:
        {{- if .Values.helm.versions }}
        - --enabled-helm-versions={{ .Values.helm.versions }}
        {{- if .Values.configureRepositories.enable }}
        {{- range $version := splitList "," .Values.helm.versions }}
        - --helm-repository-import={{ $version }}:/helm/.helm/repository/repositories.yaml
        {{- end }}
        {{- end }}
        {{- end }}
        {{- if .Values.logFormat }}
        - --log-format={{ .Values.logFormat }}
        {{- end }}
        - --git-timeout={{ .Values.git.timeout }}
        - --git-poll-interval={{ .Values.git.pollInterval }}
        {{- if .Values.git.defaultRef }}
        - --git-default-ref={{ .Values.git.defaultRef }}
        {{- end }}
        - --charts-sync-interval={{ .Values.chartsSyncInterval }}
        {{- if .Values.statusUpdateInterval }}
        - --status-update-interval={{ .Values.statusUpdateInterval }}
        {{- end }}
        - --update-chart-deps={{ .Values.updateChartDeps }}
        - --log-release-diffs={{ .Values.logReleaseDiffs }}
        {{- if .Values.workers }}
        - --workers={{ .Values.workers }}
        {{- end }}
        {{- if .Values.allowNamespace }}
        - --allow-namespace={{ .Values.allowNamespace }}
        {{- end }}
      {{- if .Values.extraEnvs }}
        env:
{{ toYaml .Values.extraEnvs | indent 8 }}
      {{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
