---

base image build:
  stage: build
  image: registry.example.com/example-namespace/anchor-build-tools:latest
  only:
    - base_image_build
  before_script:
    - cd base_image
    - export AUTH_FILE="/registry_auth.cfg"
    - echo "$DOCKER_AUTH_CONFIG" > "$AUTH_FILE"
  script:
    - SNAPSHOT=$(echo "${BASE_IMAGE}" | cut -d ':' -f 2)
    - sed -i "s/SNAPSHOT/${SNAPSHOT}/" os-core.repo
    - container=$(buildah from scratch)
    - mount_path=$(buildah mount "$container")
    - yum -c ./os-core.repo install --disablerepo=* --enablerepo=os-core --installroot="$mount_path" -y @base @core
    - yum -c ./os-core.repo --enablerepo=os-core --installroot="$mount_path" clean all
    - echo buildah commit "$container" "docker://${BUILD_REGISTRY_URL}/${BASE_IMAGE}"
    - buildah commit "$container" "docker://${BUILD_REGISTRY_URL}/${BASE_IMAGE}"
    - buildah rm "$container"
